# WARNING: This Docker Compose file is for development purpose only. Never use
# it on production
version: "3.3"
services:
  postgres: 
    build: ./postgres
    restart: always
    ports:
      - "${TEST_POSTGRES_PORT:-5434}:5432"
    environment:
      POSTGRES_USERNAME: "${TEST_POSTGRES_USERNAME:-postgres}"
      POSTGRES_PASSWORD: "${TEST_POSTGRES_PASSWORD:-postgres}"
      POSTGRES_DB: "${TEST_POSTGRES_DATABASE:-postgres}"
      # Enable SSL with self-signed certificate generated on the fly
      POSTGRES_SSL: "${TEST_POSTGRES_SSL:-1}"
  pgadmin:
    image: dpage/pgadmin4:4.20
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL:-pgadmin@localhost}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD:-pgadmin}"
